name: Build AppImage
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  version:
    name: Windsurf AppImage
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      # Get latest version from AUR PKGBUILD
      - name: Get latest version
        id: get-version
        run: |
          PKGBUILD_URL="https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=windsurf"
          PKGVER=$(curl -s $PKGBUILD_URL | grep -Po 'pkgver=\K[0-9.]+')
          echo "VERSION=$PKGVER" >> $GITHUB_ENV
          echo "DEB_URL=https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/apt/pool/main/w/windsurf/Windsurf-linux-x64-${PKGVER}.deb" >> $GITHUB_ENV

      # Download and extract .deb package
      - name: Handle .deb package
        run: |
          mkdir -p windsorf-deb
          curl -L ${{ env.DEB_URL }} -o windsorf.deb
          ar x windsorf.deb --output=windsorf-deb
          tar -xf windsorf-deb/data.tar.xz --directory=windsorf-deb

      # Prepare AppImage build environment
      - name: Setup AppImage sources
        run: |
          mkdir -p appimage-src
          cp -r windsorf-deb/usr/share/windsurf/* appimage-src/
          cp windsorf-deb/usr/share/applications/windsurf.desktop appimage-src/
          cp windsorf-deb/usr/share/windsurf/resources/app/resources/linux/code.png appimage-src/

      # Build AppImage with zsync support
      - name: Build AppImage
        id: build
        uses: valicm/appimage-bash@main
        with:
          version_url: ${{ env.DEB_URL }}
          version_file: "appimage-src/resources/app/package.json"
          version_bash: "jq -r .version"
          version_icon: "appimage-src/code.png"
          zsync: true
          app_dir: "appimage-src"
          app_exec: "bin/windsurf"

      # Upload artifacts including zsync file
      - name: Upload artifact
        if: ${{ env.APP_UPDATE_NEEDED == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Windsurf-AppImage
          path: |
            dist/*.AppImage
            dist/*.zsync

      # Release with delta updates support
      - name: Release
        if: ${{ env.APP_UPDATE_NEEDED == 'true' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Windsurf AppImage ${{ env.VERSION }}
          automatic_release_tag: latest
          prerelease: false
          files: |
            dist/*.AppImage
            dist/*.zsync
          repo_token: ${{ secrets.GITHUB_TOKEN }}
